### PR TITLE
Rename to Faros

### PR DESCRIPTION
**Pull request by Maikon**

### CODE REVIEW

**Comment by Maikon** [comment]
When you guys have time have a :eyes: on this. @christophgockel @felipesere @marosluuce

**Comment by felipesere** [comment]
I tried to run it locally and ran into a bunch of unrelated issues.
In an attempt to solve them, I have updated most all infrastructure files and upgraded Erlang and Elixir.

The issue I had was that the Alpine packages for Erlang 18.1 were released and rebuilding the base image pulled those in.

All in all this LGTM :+1:

**Comment by christophgockel** [comment]
Would it make sense to squash "Replace uppercase Lighthouse to Pharos", "Replace lowercase instances of lighthouse" and "Rename Pharos to Faros" into a commit called "Rename Lighthouse to Faros"?
I don't think the intermediate rename to "Pharos" is needed to be kept in history, isn't it?

Felipe mentioned it would make sense to keep the commit related to the infrastructure separate, though ("Update name in infrastructure files").

**Comment by Maikon** [comment]
Done.

**Comment by christophgockel** [comment]
:+1:

**Pull request merged**
