### PR TITLE
Work on styling

### PR DESCRIPTION
**Pull request by ukutaht**

### CODE REVIEW

**Comment by c-j-j** [comment]
Quite a large amount of padding on right hand side when I'm at 100% zoomed in. Are we able to improve this so it always takes up the entire width?

image

**Comment by c-j-j** [comment]
Looks good :+1:

**Comment by felipesere** [comment]
@cj we tried to center it... But then CSS happened.

**Comment by cpeak** [comment]
I have a branch called styling_feedback (https://github.com/felipesere/faros/tree/styling_feedback) where I have made a pass at what Uku was working on. I refactored the code to make it much cleaner and simpler, starting to break out things to be more repeatable, but had to stop before restyling the whole app. We can talk in person about the specific changes.

I switched the 'cards' to use Neat's layout instead of defining them manually, they flow better without any of the gap issues.

screen shot 2016-04-08 at 9 56 34 am

**Comment by ukutaht** [comment]
Thanks for the feedback @cpeak! I think I will try to replicate what you have done manually to get some learning out of this instead of just pulling in your commit.

I like how you were able to separate generic styles from classes that are actually specific to cards. I definitely need to develop the ability to step back and say: 'Hey, maybe margin: 0; padding: 0; are not really styles that are specific to a card list'.

Using neat for the cards makes so much more sense than what we were doing earlier :) Lesson: grid systems are good and we should use them.

I have to admit, I'm having a problem understanding the whole modules thing. The reason @felipesere and I didn't use the top-level `module__{whatever}` classes here is because we just didn't really know why they exist or what the pattern is about.

Do these modules represent every type of top-level, full-width section that our pages can have? If so, shouldn't the navbar and hero banner also be modules? In a real project, how many different `module__{...}` classes would you have?

If `module__normal` is going to be the standard vertical divider, should we get rid of the bottom border from it? Currently in your branch the bottom of the page has a border on it which looks a bit weird to me. Then maybe we could introduce a class that adds it back in if one needs a bottom border a module.

I realise I'm probably getting hung up on a really simple idea but I'd appreciate if you could take a minute to explain the whole concept.

**Comment by felipesere** [comment]
Thanks @cpeak for your feedback!

I sill have questions about *modules_{whatever}* and other generic classes:
Given that we can use *@mixins*, *$variables* and functions, wouldn't it make sense to reuse those (generic!) instead of class names (specific!)?
If I need to separate domain things to look the same, I can achieve that doing
```
@mixin look-like-a-card {
 // here be dragons
}

.learning-path {
  @include look-like-a-card()
  // maybe here be smaller, special dragons
}
.famous-user {
  @include look-like-a-card()
  // maybe here be famous dragons, like Drogon, Rhaegal, and Viserion
}
```
When the desired style changes, I can either add a @mixin or add variables, to keep the amount of duplication contained.

Putting generic classes (`.module__normal`, `.centered`, `.card`) on the HTML gives me so little context.  In my head, the classes should be closer to "_hooks_", or methods where the name is tells me _what_ and the actual CSS rules behind them _how_.

**Pull request merged**
